spring:
  cloud:
    gateway:

      mvc:
        routes:
          - id: banner
            uri: ${BANNER_URI:http://localhost:8089}
            predicates:
              - Path=/motd/**
            filters:
              - PrefixPath=/api
              - AddResponseHeader=X-Powered-By,MICRO GATEWAY
#          - id: frontend
#            uri: ${FRONTEND_URI:http://localhost:8000}
#            predicates:
#              - Path=/**
#            filters:
#              - AddResponseHeader=X-Powered-By, MICRO GATEWAY
